name: dphand_panda_pick-place

task_name: ${name}

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [512, 3]
      type: point_cloud
    agent_pos:
      shape: [32]  # 7末端执行器位置 + 22关节角度
      type: low_dim
    full_state: # full state并不会输入到dp3 encoder中，因此输入只有前面两个
      shape: [65]  # 7末端执行器位置 + 7物体姿态 + 7目标姿态 + 22关节角度 + 22关节速度
      type: low_dim
  action:
    shape: [29]  # 7末端执行器位置 + 22关节角度

env_runner:
  _target_: diffusion_policy_3d.env_runner.dphand_pc_runner.DphandPointCloudRunner
  eval_episodes: 20
  max_steps: 1000  # 每个episode的最大步数
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 30
  num_points: 512
  use_object_pos: true
  render_mode: "rgb_array"
  use_tactile_obs: false
  use_object_pos: true
  
dataset:
  _target_: diffusion_policy_3d.dataset.dphand_dataset.DphandDataset
  zarr_path: data/1014/pick_and_place_47demos_1014_pc_and_pos.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
