name: dphand_panda_pick-place

image_shape: &image_shape [3, 84, 84]
shape_meta: &shape_meta
  obs:
    front:
      shape: *image_shape
      type: rgb
    wrist:
      shape: *image_shape
      type: rgb
    agent_pos:
      shape: [29]  # 7末端执行器位置 + 22关节角度
      type: low_dim
  action:
    shape: [29]  # 7末端执行器位置 + 22关节角度

env_runner:
  _target_: diffusion_policy_3d.env_runner.panda_image_runner.DphandImageRunner
  env_config: "pick_cube_env_cfg"
  eval_episodes: 20
  max_steps: 300  # 每个episode的最大步数
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 30
  render_mode: "rgb_array"

dataset:
  _target_: diffusion_policy_3d.dataset.dphand_dataset.DphandImageDataset
  zarr_path: data/1014/pick_and_place_47demos_1014.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
