name: pick_and_place_pc_tactile

task_name: ${name}

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [512, 3]
      type: point_cloud
    agent_pos:
      shape: [29]
      type: low_dim
    tactile/thumb_tip_cam:
        shape: [84, 84]
        type: depth
    tactile/index_tip_cam:
      shape: [84, 84]
      type: depth
  action:
    shape: [29]

env_runner:
  _target_: diffusion_policy_3d.env_runner.dphand_pc_runner.DphandPointCloudRunner
  eval_episodes: 20
  max_steps: 1000
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 30
  num_points: 512
  use_tactile_obs: true
  render_mode: "rgb_array"

dataset:
  _target_: diffusion_policy_3d.dataset.dphand_dataset.DphandDataset
  zarr_path: data/1117/pick_and_place_60demos_1117_pc_tactile.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
  shape_meta: ${shape_meta}
