name: dphand_panda_pick-place

image_shape: &image_shape [3, 84, 84]
shape_meta: &shape_meta
  obs:
    image:
      shape: *image_shape
      type: rgb
    agent_pos:
      shape: [29]  # 7末端执行器位置 + 22关节角度
      type: low_dim
  action:
    shape: [29]  # 7末端执行器位置 + 22关节角度

env_runner:
  _target_: diffusion_policy_3d.env_runner.panda_image_runner.DphandImageRunner
  env_config: "pick_cube_env_cfg"
  eval_episodes: 1
  max_steps: 300  # 每个episode的最大步数
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 30
  render_mode: "rgb_array"

dataset:
  _target_: diffusion_policy_3d.dataset.dphand_dataset.DphandImageDataset
  zarr_path: data/0929/panda_pick_and_place_0929_with_pointcloud.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
