name: dphand_panda_pick-place

task_name: ${name}

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [512, 3]
      type: point_cloud
    agent_pos:
      shape: [29]  # 7末端执行器位置 + 22关节角度
      type: low_dim
    full_state:
      shape: [65]  # 7末端执行器位置 + 7物体姿态 + 7目标姿态 + 22关节角度 + 22关节速度
      type: low_dim
  action:
    shape: [29]  # 7末端执行器位置 + 22关节角度

env_runner:
  _target_: diffusion_policy_3d.env_runner.panda_runner.DphandPandaRunner
  eval_episodes: 1
  max_steps: 300  # 每个episode的最大步数
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 30
  num_points: 1024

dataset:
  _target_: diffusion_policy_3d.dataset.dphand_dataset.DphandDataset
  zarr_path: data/1014/pick_and_place_47demos_1014_with_pointcloud.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
