name: dphand_pick-place

task_name: ${name}

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [1024, 6]
      type: point_cloud
    agent_pos:
      shape: [56]  # 28个关节 * 2 (位置+速度) = 56
      type: low_dim
    full_state:
      shape: [70]  # 56 (机器人状态) + 7(物体位置+旋转) = 63
      type: low_dim
  action:
    shape: [28]  # dphand有28个关节

env_runner:
  _target_: diffusion_policy_3d.env_runner.dphand_runner.DphandRunner
  eval_episodes: 10
  max_steps: 300  # 每个episode的最大步数
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 30
  device: ${training.device}
  use_point_crop: False
  num_points: 1024
  render_size: 128

dataset:
  _target_: diffusion_policy_3d.dataset.dphand_dataset.DphandDataset
  zarr_path: data/dphand_0919/dphand_pick_cube_expert_with_pointcloud.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
