name: dphand_panda_pick-place

task_name: ${name}

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [31]  # 7末端执行器位置 + 22关节角度 + 3物体位置 但是目前少了一个小拇指
      type: low_dim
    full_state:
      shape: [63]  # 
      type: low_dim
  action:
    shape: [29]  # 7末端执行器位置 + 22关节角度

env_runner:
  _target_: diffusion_policy_3d.env_runner.dphand_panda_runner.DphandPandaRunner
  eval_episodes: 5
  max_steps: 300  # 每个episode的最大步数
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  device: ${training.device}
  use_point_crop: False
  num_points: 1024
  render_size: 128

dataset:
  _target_: diffusion_policy_3d.dataset.dphand_dataset.DphandDataset
  zarr_path: data/panda/panda_pick_and_place_0926_1_with_pointcloud.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
